### ISSUE TITLE
Not compatible with DNN 8.x due to use of DnnGrid

### ISSUE THREAD

**Issue by efficiondave** [EngageSoftware/Engage-Jackrabbit#8]
With the Telerik controls being deprecated, JackRabbit throws an error when used on a DNN 8 site.

**Comment by efficiondave** [comment]
Since I had an updated site throwing an error, I cloned the code and made the needed updates to use the DotNetNuke.Web.Deprecated.dll. This isn't the right long term fix as the DnnGrid really needs to be replaced but it makes it work for now. 
I also updated the project file to use the NuGet Dnn.Platform package instead of the DNN 6.2 references that were included. Same with the WebFormsMVP package. 
Let me know if you want me to push any of these changes as a branch or something else.

**Comment by bdukes** [comment]
Thanks, @efficiondave.  We've started work on a new version of the module that doesn't use the grid.  If you're interested in trying it out, you can [view the latest build](http://teamcity.engagesoftware.com/viewType.html?buildTypeId=bt4) from the [v2 branch](/EngageSoftware/Engage-Jackrabbit/tree/v2), and download the install-able package from that build's artifacts.
